# Site settings
title: Sandy Kahrod - Product & Technology Transformation Leader
description: Award-winning product leader specialising in technology transformation, portfolio strategy, and scaling internal systems for senior leadership teams.
baseurl: ""
url: "https://sandykahrod.co.uk"

# Social media
linkedin_username: sandykahrod
email: skahrod@hotmail.com
phone: "07961 430242"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /insights/:title/

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# SEO
author: Sandy Kahrod
twitter:
  username: sandykahrod
  card: summary

# Default values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Sandy Kahrod"