# Site settings
title: Sandy Kahrod - Thoughtful Technology Transformation
description: Award-winning product leader who believes the most powerful technology transformations happen when we honour both people and performance. Creating meaningful change that resonates throughout organisations.
baseurl: ""
url: "https://sandykahrod.co.uk"

# Social media
linkedin_username: sandykahrod
email: skahrod@hotmail.com
phone: "07961 430242"

# Brand personality
tagline: "Transform with Purpose. Build with Heart. Lead with Impact."
approach: "Where technical expertise meets human understanding"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /insights/:title/

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - DEPLOYMENT-CHECKLIST.md

# SEO
author: Sandy Kahrod
twitter:
  username: sandykahrod
  card: summary

# Default values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Sandy Kahrod"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Site personality and values
values:
  - "People-centred strategy that honours relationships and empathy"
  - "Meaningful results that represent real human impact"
  - "Sustainable excellence through nurturing growth and capability"
  - "Thoughtful leadership that creates lasting positive change"

# Services focus areas
services:
  - name: "Technology Transformation Leadership"
    description: "Thoughtful, people-centred transformation strategy"
    icon: "🌱"
  - name: "Internal Platform & Systems Strategy" 
    description: "Building sustainable, scalable internal capabilities"
    icon: "✨"
  - name: "Portfolio & Product Management Excellence"
    description: "Strategic portfolio ownership with human impact focus"
    icon: "📊"
  - name: "Team Leadership & Organisational Change"
    description: "Creating environments where people and teams thrive"
    icon: "🤝"