# Site settings
title: Sandy Kahrod - Thoughtful Technology Transformation
description: Award-winning product leader who believes the most powerful technology transformations happen when we honour both people and performance. Creating meaningful change that resonates throughout organisations.
baseurl: ""
url: "https://sandykahrod.co.uk"

# Contact information
linkedin_username: sandykahrod
email: skahrod@hotmail.com
phone: "07961 430242"

# Brand personality
tagline: "Transform with Purpose. Build with Heart. Lead with Impact."

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /insights/:title/

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - DEPLOYMENT-CHECKLIST.md

# SEO
author: Sandy Kahrod
twitter:
  username: sandykahrod
  card: summary

# Default values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Sandy Kahrod"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"